[package]
name = "n2k-test"
version = "0.1.0"
edition = "2018"

[dependencies]
n2k = { path = "../n2k" }
structopt = "0.3.21"
canutils = "1.0.0"
embedded-hal-can = { git = "https://github.com/technocreatives/embedded-hal-can" }
nb = "1.0.0"
env_logger = "0.8.3"
log = "0.4.14"
bitvec = { version = "0.22.3" }
defmt = "0.3.6"
tokio = { version = "0.3.0", features = ["rt-multi-thread", "macros"] }
